[package]
name = "murl-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1"
murl-core = { path = "../crates/murl-core" }

[[bin]]
name = "parse_murl"
path = "fuzz_targets/parse_murl.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_manifest"
path = "fuzz_targets/parse_manifest.rs"
test = false
doc = false
bench = false

[[bin]]
name = "canonical_json"
path = "fuzz_targets/canonical_json.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1
